
aws:
  region: us-east-2
  s3_bucket: sales-prediction-mlops
  s3_data_path: data/raw/sales_data.csv
  s3_artifacts_path: data/artifacts/


mlflow:
  experiment_name: sales-prediction
  tracking_uri: http://18.191.95.224

model:
  name: sales-prediction-model
  target_column: sales_amount
  test_size: 0.2
  random_state: 42
  algorithm: LinearRegression

sagemaker:
  endpoint_name: sales-prediction-endpoint
  instance_type: ml.t2.medium

fastapi:
  host: 0.0.0.0
  port: 8000
